warehouse_index:
    pattern: /
    defaults:  { _controller: BiSight\Portal\Controller\WarehouseController::indexAction }

warehouse_view:
    pattern: /{accountName}/{warehouseName}
    defaults:  { _controller: BiSight\Portal\Controller\WarehouseController::viewAction }

table_index:
    pattern: /{accountName}/{warehouseName}/tables
    defaults:  { _controller: BiSight\Portal\Controller\TableController::indexAction }

table_view:
    pattern: /{accountName}/{warehouseName}/tables/{tableName}
    defaults:  { _controller: BiSight\Portal\Controller\TableController::viewAction }

table_description:
    pattern: /{accountName}/{warehouseName}/tables/{tableName}/description
    defaults:  { _controller: BiSight\Portal\Controller\TableController::descriptionAction }

table_download:
    pattern: /{accountName}/{warehouseName}/tables/{tableName}/download
    defaults:  { _controller: BiSight\Portal\Controller\TableController::downloadAction }

olapschema_view:
    pattern: /{accountName}/{warehouseName}/olapschema
    defaults:  { _controller: BiSight\Portal\Controller\OlapController::viewSchemaAction }

lattice_index:
    pattern: /{accountName}/{warehouseName}/lattices
    defaults:  { _controller: BiSight\Portal\Controller\LatticeController::indexAction }

lattice_view:
    pattern: /{accountName}/{warehouseName}/lattices/{latticecode}
    defaults:  { _controller: BiSight\Portal\Controller\LatticeController::viewAction }

lattice_download:
    pattern: /{accountName}/{warehouseName}/lattices/{latticecode}/download
    defaults:  { _controller: BiSight\Portal\Controller\LatticeController::downloadAction }

lattice_report_index:
    pattern: /{accountName}/{warehouseName}/latticereports
    defaults:  { _controller: BiSight\Portal\Controller\LatticeController::indexLatticeReportAction }

lattice_report_view:
    pattern: /{accountName}/{warehouseName}/latticereport/{reportname}
    defaults:  { _controller: BiSight\Portal\Controller\LatticeController::viewLatticeReportAction }
