index:
    pattern: /
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::indexAction }

datawarehouse:
    pattern: /dw/{dwcode}
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::viewDataWarehouseAction }

table_index:
    pattern: /dw/{dwcode}/tables
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::tableIndexAction }

table_view:
    pattern: /dw/{dwcode}/tables/{tablename}
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::tableViewAction }

schema_view:
    pattern: /dw/{dwcode}/olapschema
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::viewOlapSchemaAction }

datasource_view:
    pattern: /dw/{dwcode}/datasource/{dscode}
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::viewDataSourceAction }
