index:
    pattern: /
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::indexAction }

datawarehouse:
    pattern: /dw/{dwcode}
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::viewDataWarehouseAction }

table_index:
    pattern: /dw/{dwcode}/tables
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::tableIndexAction }

table_view:
    pattern: /dw/{dwcode}/tables/{tablename}
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::tableViewAction }

olapschema_view:
    pattern: /dw/{dwcode}/olapschema
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::viewOlapSchemaAction }

dataset_view:
    pattern: /dw/{dwcode}/dataset/{dscode}
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::viewDataSetAction }

report_view:
    pattern: /dw/{dwcode}/report/{reportname}
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::viewReportAction }
