index:
    pattern: /
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::indexAction }

datawarehouse:
    pattern: /dw/{dwcode}
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::viewDataWarehouseAction }

table_index:
    pattern: /dw/{dwcode}/tables
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::tableIndexAction }

table_view:
    pattern: /dw/{dwcode}/tables/{tablename}
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::tableViewAction }

table_download:
    pattern: /dw/{dwcode}/tables/{tablename}/download
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::tableDownloadAction }

olapschema_view:
    pattern: /dw/{dwcode}/olapschema
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::viewOlapSchemaAction }

dataset_view:
    pattern: /dw/{dwcode}/dataset/{dscode}
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::viewDataSetAction }

dataset_index:
    pattern: /dw/{dwcode}/dataset
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::indexDataSetAction }

report_index:
    pattern: /dw/{dwcode}/report
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::indexReportAction }

report_view:
    pattern: /dw/{dwcode}/report/{reportname}
    defaults:  { _controller: BiSight\Portal\Controller\PortalController::viewReportAction }
